### ISSUE TITLE
Power By Disappears 

### ISSUE THREAD

**Issue by viruscmd** [devtees/shirt-ideas#45] opened 2015-10-30 13:36 UTC
When you hover over Joel Glovier in the footer the words "Powered By" disappear.

**Comment by viruscmd** [comment] 2015-10-30 13:38
Also the same happens when you hover over shopify "Joel Glovier" disappears.

**Comment by jglovier** [comment] 2015-10-30 13:45
LOL what a strange bug. Thanks for pointing it out.

**Comment by jglovier** [comment] 2015-11-01 18:33
This appears to be a Chrome bug as I can't reproduce it in Firefox or Safari. Going to keep digging to find a workaround.

**Comment by jglovier** [comment] 2015-11-01 19:28
Looked for stray markup and even checked the HTML validator for clues, but couldn't find anything. Closing as a Chrome bug. Thanks again for the heads up.

**Closed by jglovier** 2015-11-01 19:28 UTC
